export enum ResponseMessage {
  CREATE_BOOK_SUCCESS = "To-do book successfully created",
  CREATE_BOOK_FAIL = "To-do book cannot be created",
  DELETE_BOOK_SUCCESS = "To-do book successfully deleted",
  DELETE_BOOK_NOTFOUND = "To-do book has already been deleted",
  DELETE_BOOK_FAIL = "To-do book cannot be deleted",
  GET_BOOK_SUCCESS = "To-do book successfully retrieved",
  GET_BOOK_FAIL = "To-do book not found",
  UPDATE_BOOK_SUCCESS = "To-do book successfully updated",
  UPDATE_BOOK_FAIL = "To-do book cannot be updated",
  CREATE_COMMENT_SUCCESS = "Comment successfully added",
  CREATE_COMMENT_FAIL = "Comment could not be added",
  DELETE_COMMENT_SUCCESS = "Comment successfully deleted",
  DELETE_COMMENT_NOTFOUND = "Comment has already been deleted",
  DELETE_COMMENT_FAIL = "Comment could not be deleted",
  UPDATE_COMMENT_SUCCESS = "Comment successfully updated",
  UPDATE_COMMENT_FAIL = "Comment could not be updated",
  GET_COMMENT_SUCCESS = "Comment successfully retrieved",
  GET_COMMENT_FAIL = "Comment not found",
  ERROR = "Unknown error.",
  INVALID_REQUEST = "Invalid Request!",
  GET_ITEM_ERROR = "Item does not exist",
}
