export enum ResponseMessage {
  CREATE_BOOK_SUCCESS = "To-do book successfully created",
  CREATE_BOOK_FAIL = "To-do book cannot be created",
  DELETE_BOOK_SUCCESS = "To-do book successfully deleted",
  DELETE_BOOK_NOTFOUND = "To-do book has already been deleted",
  DELETE_BOOK_FAIL = "To-do book cannot be deleted",
  GET_BOOK_SUCCESS = "To-do book successfully retrieved",
  GET_BOOK_FAIL = "To-do book not found",
  UPDATE_BOOK_SUCCESS = "To-do book successfully updated",
  UPDATE_BOOK_FAIL = "To-do book cannot be updated",
  CREATE_TASK_SUCCESS = "Task successfully added",
  CREATE_TASK_FAIL = "Task could not be added",
  DELETE_TASK_SUCCESS = "Task successfully deleted",
  DELETE_TASK_NOTFOUND = "Task has already been deleted",
  DELETE_TASK_FAIL = "Task could not be deleted",
  UPDATE_TASK_SUCCESS = "Task successfully updated",
  UPDATE_TASK_FAIL = "Task could not be updated",
  GET_TASK_SUCCESS = "Task successfully retrieved",
  GET_TASK_FAIL = "Task not found",
  ERROR = "Unknown error.",
  INVALID_REQUEST = "Invalid Request!",
  GET_ITEM_ERROR = "Item does not exist",
}
